name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  ANY_SECRET: ${{ secrets.ANY_SECRET }}


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - name: Run Unit Tests
        run: |
          echo ${{ secrets.ANY_SECRET }}
          echo ${{ env.ANY_SECRET }}
          echo ${{ env.TEST_ENV }}
          echo ${{ secrets.SSH_KEY }}
          export SSH_K=${{ secrets.SSH_KEY }}
          export TEST_KEY=hi
          echo $TEST_KEY
          echo ${{ secrets.SSH_KEY_NEW }}
          export SSH_K='${{ secrets.SSH_KEY_NEW }}'
